# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password_generator.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(398, 277)
        self.numbers_cb = QtWidgets.QCheckBox(Form)
        self.numbers_cb.setGeometry(QtCore.QRect(200, 60, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.numbers_cb.setFont(font)
        self.numbers_cb.setObjectName("numbers_cb")
        self.specialcharacter_cb = QtWidgets.QCheckBox(Form)
        self.specialcharacter_cb.setGeometry(QtCore.QRect(200, 90, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.specialcharacter_cb.setFont(font)
        self.specialcharacter_cb.setObjectName("specialcharacter_cb")
        self.generatebtn = QtWidgets.QPushButton(Form)
        self.generatebtn.setGeometry(QtCore.QRect(90, 210, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.generatebtn.setFont(font)
        self.generatebtn.setObjectName("generatebtn")
        self.passwordlength_label = QtWidgets.QLabel(Form)
        self.passwordlength_label.setGeometry(QtCore.QRect(20, 130, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.passwordlength_label.setFont(font)
        self.passwordlength_label.setObjectName("passwordlength_label")
        self.showpassword_tb = QtWidgets.QLineEdit(Form)
        self.showpassword_tb.setGeometry(QtCore.QRect(10, 10, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.showpassword_tb.setFont(font)
        self.showpassword_tb.setText("")
        self.showpassword_tb.setAlignment(QtCore.Qt.AlignCenter)
        self.showpassword_tb.setObjectName("showpassword_tb")
        self.radioButton_6 = QtWidgets.QRadioButton(Form)
        self.radioButton_6.setGeometry(QtCore.QRect(30, 160, 41, 17))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_8 = QtWidgets.QRadioButton(Form)
        self.radioButton_8.setGeometry(QtCore.QRect(30, 180, 41, 17))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_16 = QtWidgets.QRadioButton(Form)
        self.radioButton_16.setGeometry(QtCore.QRect(100, 180, 41, 17))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_24 = QtWidgets.QRadioButton(Form)
        self.radioButton_24.setGeometry(QtCore.QRect(190, 170, 31, 17))
        self.radioButton_24.setObjectName("radioButton_24")
        self.radioButton_12 = QtWidgets.QRadioButton(Form)
        self.radioButton_12.setGeometry(QtCore.QRect(100, 160, 41, 17))
        self.radioButton_12.setObjectName("radioButton_12")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 50, 161, 81))
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        self.generatebtn.clicked.connect(Form.generate_password)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Password Generator"))
        self.numbers_cb.setText(_translate("Form", "Numbers"))
        self.specialcharacter_cb.setText(_translate("Form", "Special Characters"))
        self.generatebtn.setText(_translate("Form", "Generate"))
        self.passwordlength_label.setText(_translate("Form", "Password Length"))
        self.radioButton_6.setText(_translate("Form", "6"))
        self.radioButton_8.setText(_translate("Form", "8"))
        self.radioButton_16.setText(_translate("Form", "16"))
        self.radioButton_24.setText(_translate("Form", "24"))
        self.radioButton_12.setText(_translate("Form", "12"))
        self.label.setText(_translate("Form", "Lowercase and Uppercase are generated by default. Tick the Numbers and Special Characters checkboxes if you want to make your password more stronger."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
